global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'school-connect-app'
    metrics_path: '/api/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['app:8081']
        labels:
          application: 'school-connect'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
